### ISSUE TITLE
Data View: Filters

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform-client-mzima#596]
Filter posts by Surveys

- [x] Logging in, navigate to Data View
- [x] Verify count on `Results: 176` and `Current results: 20/176`
- [x] Click Clear to unselect all Selected Surveys
- [x] Verify Results count is 0
- [x] Select the survey `Counting and Results`
- [x] Verify Result count is 9, matching count on Survey
- [x] Select Survey  `Polling Station Administration`
- [x] Verify Result count is now 13
- [x] Select Survey `Positive events`
- [x] Verify Result count is now 22
- [x] Verify `Current Results` figure is 20/22
- [x] Click `Filters` to reveal filters
- [x] Click `Clear All filters`
- [x] Verify count on `Results: 176` and `Current results: 20/176`

**Comment by shakirandagire** [comment]
@AmTryingMyBest could you assign me to this issue

**Comment by theobadha** [comment]
Closing as done.
