### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform-client-mzima#597]
- [ ] Login as an admin
- [ ] Navigate to collections 
- [ ] Create a new collection
- [ ] Click Add Collection
  - [ ] Enter name as: "Automated Collection"
  - [ ] Enter Description as: "Automated Description"
  - [ ] Select "Only me" radio button
  - [ ] Click Save
- [ ] Add post to Collection
- [ ] Verify post added to Collection

**Comment by shakirandagire** [comment]
@AmTryingMyBest Can you assign me to this issue

**Comment by shakirandagire** [comment]
@AmTryingMyBest I have already raised a PR for the ticket. Could you please assign me as well.
