### ISSUE TITLE
Login: Login Programatically

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform-client-mzima#600]
- [x] Test the user-flow through the UI just one time.
- [x] Subsequent tests will have the platform logged into programatically.

**Comment by Caleno-R** [comment]
Hi @AmTryingMyBest I am interested in this issue.  Please assign it to me.

**Comment by shakirandagire** [comment]
Hi @AmTryingMyBest this issue does not seem to be worked on. Could you assign me to it?
