### ISSUE TITLE
General Settings: Edit page

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform-client-mzima#601]
- [x] Navigate to General Settings page
- [x] Edit. deployment name
- [x] Edit Description
- [x] Save
- [x] Verify changes reflect
- [x] Verify API Key field should have a value

**Comment by Caleno-R** [comment]
Hi, @AmTryingMyBest please assign this issue to me.

**Comment by Caleno-R** [comment]
@AmTryingMyBest I have created a pull request that will fix this issue
[pull request](https://github.com/ushahidi/platform-client-mzima/pull/648)

**Comment by shakirandagire** [comment]
@AmTryingMyBest This issue does not seem to have work done on it. Could you assign me to it.
