### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#606]
Automate and verify creation of a parent category
- [x] Log in as admin
- [x] Navigate to categories (/settings/categories)
- [x] Click Add Category
- [x] Enter Category name (Automated Category)
- [x] Enter Description name (Automated Description)
- [x] Leave Parent Category name empty
- [x] Verify Everyone is selected for category
- [x] Save to create Category
- [x] Verify newly created category exists in list of Categories

**Comment by oyenuga17** [comment]
Hi @AmTryingMyBest, please I'd love to try out this issue
