### ISSUE TITLE
Settings - General

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#609]
- [x] Navigate to Settings - "…/settings/general"
- [x] Add text " - Automated" to the Deployment name
- [x] Click Save button
- [x] Verify deployment name changes top right side
- [x] Edit description field
- [x] Click Save button
- [x] Verify description is updated

**Comment by Caleno-R** [comment]
Hi @AmTryingMyBest, I would like to work on this issue. Would you please assign it to me?

**Comment by Caleno-R** [comment]
@AmTryingMyBest I have created a pull request that will fix this issue
[pull request](https://github.com/ushahidi/platform-client-mzima/pull/648)
