### ISSUE TITLE
Surveys - submit a response to a Survey

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#614]
- [x] Navigate to Surveys page
- [x] Open Survey with name "Full Length Survey-with image-field-don't delete"
- [x] Type in responses to all fields in the survey as such:
- [x] Title => "Automated Title Response"
- [x] Description => "Automated Description Response"
- [x] Short Text Field => "Automated Short Text Response"
- [x] Long Text Field => "Automated Long Text Response"
- [x] Number Decimal Field => 99.9
- [x] Number Integer Field => 100
- [x] Date & Time Field => Click checkmark to accept current time
- [x] Select Field => Select S1
- [x] Radio Button => Select R2
- [x] Checkbox Field => Select F3
- [x] Click Submit to send response to Survey
- [x] Verify confirmation modal
- [x] Click Ok to dismiss portal
- [x] Verify user is sent to Data View

**Comment by oyenuga17** [comment]
@AmTryingMyBest please assign me this issue. I already raised a pr for it here #632 🙏
