### ISSUE TITLE
[USH-913] Mobile Client: Cannot connect to local backend API to app yet

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform-client-mzima#621]
#### Issue description

The mobile client cannot connect to and therefore does not allow for testing or developing with the backend API locally.

#### How to reproduce the issue

- Follow the instructions to install and run the backend locally on your computer on the backend API's readme: https://github.com/ushahidi/platform#setup-essentials
- Test mobile client for android and/or iOS to see that issue described is present. Follow the instructions to clone, setup and launch the mobile client locally at: https://github.com/ushahidi/platform-client-mzima#platform-client-mzima.
- Go to the mobile client's env.json file and change the backend_url to your backend's localhost url as shown in the readme.
- On the app's user interface, go through or skip the mobile app's walkthrough, then navigate to the list of deployments. The local backend is not in the list.

#### Suggested/expected output

At the point where app detects that the backend url returned uses localhost, make it possible to find the locally hosted deployment on the list. It should run the locally hosted app successfully.

#### Screenshot
![Screenshot 2023-10-08 at 10 42 00](https://github.com/ushahidi/platform-client-mzima/assets/45185388/abd37723-94aa-42ea-af4d-3e32b451c6dc)

If you can't see the screenshot added on github, open the issue on linear (request for access to linear through our Gitter community channel or on slack).

<sub>[USH-913](https://linear.app/ushahidi/issue/USH-913/mobile-client-cannot-connect-to-local-backend-api-to-app-yet)</sub>

**Comment by tuxpiper** [comment]
A couple of suggestions:

* Using ngrok on the API endpoint
* Use the LAN IP assigned to one other of the interfaces in your computer (i.e. your wifi network interface IP address given by `ifconfig en0`)
