### ISSUE TITLE
[USH-916] Rename menu-list-links Angular component name to better reflect its purpose

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform-client-mzima#623]
#### Issue description

Rename `menu-list-links` Angular component name to better reflect its purpose in the web  application

#### How to reproduce or check for this issue

* Follow the instructions to launch the web client locally at: [https://github.com/ushahidi/platform-client-mzima#platform-client-mzima](https://github.com/ushahidi/platform-client-mzima#platform-client-mzima).
* Check the code for the component with name `menu-list-links`

#### Suggested/expected output

Rename the `menu-list-links` Angular component to `menu-nav-views` instead (without breaking the functionality).

<sub>From [SyncLinear.com](https://synclinear.com) | [USH-916](https://linear.app/ushahidi/issue/USH-916/rename-menu-list-angular-component-name-to-better-reflect-its-purpose)</sub>

**Comment by oyenuga17** [comment]
Please assign me
 .. when i checked the files .. I only saw a file named "menu-list-link"  could that be the intended file?

**Comment by Ifycode** [comment]
Ha! yes nice catch @oyenuga17 That was a mistake. Thank you. Corrected now in the issue title and description 👍🏼

**Comment by Ifycode** [comment]
About assigning you to hacktoberfest issues @oyenuga17 
We have a guide for **Hacktoberfest 2023** that spells out how to go about contributing specifically for hacktoberfest. Please refer to my previous 2 comments to have an idea of when/how to ask for assignment on Hactoberfest issues: https://github.com/ushahidi/platform-client-mzima/issues/626#issuecomment-1754348827 and https://github.com/ushahidi/platform-client-mzima/issues/624#issuecomment-1754355913

**Comment by MugoBrian** [comment]
Hello @Ifycode. Kindly assign me this issue.

**Comment by Ifycode** [comment]
Assigned to you @MugoBrian 👍🏼
