### ISSUE TITLE
[USH-918] Rename menu-list-non-links Angular component name to better reflect its purpose

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform-client-mzima#624]
#### Issue description

Rename `menu-list-non-links` Angular component name to better reflect its purpose in the web  application

#### How to reproduce or check for this issue

* Follow the instructions to launch the web client locally at: [https://github.com/ushahidi/platform-client-mzima#platform-client-mzima](https://github.com/ushahidi/platform-client-mzima#platform-client-mzima).
* Check the code for the component with name `menu-list-non-links`

#### Suggested/expected output

Rename the `menu-list-non-links` Angular component to `menu-modal-popups` instead (without breaking the functionality).

<sub>[USH-918](https://linear.app/ushahidi/issue/USH-918/rename-menu-list-non-links-angular-component-name-to-better-reflect)</sub>

**Comment by oyenuga17** [comment]
Please assign me

**Comment by Ifycode** [comment]
Hi @oyenuga17
I will be closing the PR you sent for this issue for now as it is counted spam, reason stated here: https://github.com/ushahidi/platform-client-mzima/issues/626#issuecomment-1754348827

Once your first/previous PR has been reviewed and approved, you are welcome to come back to add a comment that you would like to be assigned to this issue.
That is, if no one has requested to be assigned or assigned before you commented again.

**Comment by oyenuga17** [comment]
please assign me

**Comment by Ifycode** [comment]
Assigned to you @oyenuga17 👍🏼

**Comment by MugoBrian** [comment]
@oyenuga17, you did nice a job! I noticed that in the `menu-modal-components. spec.ts` (The test file) there's an error `Cannot find module './menu-list-non-links.component' or its corresponding type declarations` 
You forgot to make the necessary changes to reflect the recent changes (renaming menu-list-non-links to menu-modal-popups). 

@Ifycode , is it necessary for the `menu-modal-components. spec.ts` to be changed also?

**Comment by Ifycode** [comment]
Nice catch @MugoBrian. Although the focus is not on the test files for now as we don't have any functional tests. If you feel is something to be be fixed, you can send a separate pull request to help fix it 👍🏼

**Comment by Ifycode** [comment]
You may also want to see my review comment on @shakirandagire's PR here: https://github.com/ushahidi/platform-client-mzima/pull/661#pullrequestreview-1694112442
