### ISSUE TITLE
[USH-919] Add pull request template for platform client (mzima)

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform-client-mzima#625]
#### Issue description and expected output/solution

Prevent "from scratch" writing of pull request descriptions when contributors are submitting pull requests - add a pull request template for [platform client (mzima)](https://github.com/ushahidi/platform-client-mzima). How to add a pull request template?

* Take a clue from the [legacy platform client's .github folder](https://github.com/ushahidi/platform-client)
* Also see [Github documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

<sub>From [SyncLinear.com](https://synclinear.com) | [USH-919](https://linear.app/ushahidi/issue/USH-919/add-pull-request-template-for-platform-client-mzima)</sub>

**Comment by shakirandagire** [comment]
@Ifycode Could you assign me to this

**Comment by Ifycode** [comment]
Assigned to you @shakirandagire 
Please indicate here that you are participating in hacktoberfest here: https://github.com/ushahidi/platform/discussions/4650
