### ISSUE TITLE
[USH-920] Complete the steps to enable bot automate adding contributors to the platform client (mzima)

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform-client-mzima#626]
#### Description
All you need to work on is step 3 from the [all contributors doc page](https://allcontributors.org/docs/en/bot/installation.). Don't bother about steps 1 and 2 from the all contributors doc page.

#### Expected solution
In summary:
- Add the .all-contributorsrc file to the root of the [platform client (mzima) repo](https://github.com/ushahidi/platform-client-mzima)
- Follow example from the [backend platform API's .all-contributorsrc file](https://github.com/ushahidi/platform/blob/develop/.all-contributorsrc), to add content to the .all-contributorsrc file you created. Note: The content should be modified to suit the platform client (mzima) repo accordingly, and the contributors property should have an empty array like this instead: `"contributors": []`

<sub>[USH-920](https://linear.app/ushahidi/issue/USH-920/complete-the-steps-to-enable-bot-automate-adding-contributors)</sub>

**Comment by oyenuga17** [comment]
please assign me to this

**Comment by Ifycode** [comment]
Yes assigned to you @oyenuga17 
Oh... I see you have submitted a pull request for it. Since this is the first one you requested for and since you are the only one on this thread, I will allow your submission (PR) for this issue.

The other PRs you sent for the other issues, I will have to close them for now. Reason is you can only work on one issue at a time as stated in our [Hacktoberfest 2023](https://github.com/ushahidi/platform/discussions/4650) guide.

You also have to share your setup info as written in the guide, even if you have shared it for Outreachy or for any other events going on in Ushahidi.
