### ISSUE TITLE
[USH-901] CAM 2023: Routing to "post not found"

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform-client-mzima#627]
**Issues**

* "Post not found" design does not look good on resize from desktop to tablet and mobile
* Tablet and mobile re-routes to "page not found" instead of "post not found", same thing on resize back to desktop
* It will be nice for "Post not found" to have its own route/url, even though it only occupies some part of the page

**Video**

[routing-post-not-found.mov](https://uploads.linear.app/f1df6e34-3bca-4ade-bb48-e6a457e64091/178bd4dc-0f02-4c6f-a7ca-69ba442ecc7b/37ebfb74-7a59-4cb8-8c2c-815ca1974e1b)

If you can't see/play the video added on github, open the issue on linear (request for access to linear through our Gitter community channel or on slack).

<sub>From [SyncLinear.com](https://synclinear.com) | [USH-921](https://linear.app/ushahidi/issue/USH-921/[ush-901]-cam-2023-routing-to-post-not-found)</sub>

**Comment by Formasitchijoh** [comment]
@Ifycode i dont have access to the Gitter or slack channel can you please help with it to access the video

**Comment by Ifycode** [comment]
This is also not a straightforward issue @Formasitchijoh 
Needs to be removed from GitHub. Don't worry about this one too.

**Comment by Formasitchijoh** [comment]
@Ifycode  Thanks for your advice. Could you elaborate on the complexity of the issue? I'm eager to contribute effectively. Also, feel free to suggest another area where I can be of assistance

**Comment by Ifycode** [comment]
Hello again @Formasitchijoh 
It's not even about the complexity of the issue only. For this issue (and those other issues I told you to leave for now), the main problem is that how some things should eventually work still needs to be finalised.
We want to avoid the case where you as a contributor are just doing merry-go-round on an issue for months without resolution because of this.

You can check back tomorrow (Monday) for instructions on where to get issues to work on.
> Response usually don't come on weekends

**Comment by Formasitchijoh** [comment]
> Hello again @Formasitchijoh It's not even about the complexity of the issue only. For this issue (and those other issues I told you to leave for now), the main problem is that how some things should eventually work still needs to be finalised. We want to avoid the case where you as a contributor are just doing merry-go-round on an issue for months without resolution because of this.
> 
> You can check back tomorrow (Monday) for instructions on where to get issues to work on.
> 
> > Response usually don't come on weekends

Definitely ,i appreciate your  detailed clarification  @Ifycode , Thank you

**Comment by Ifycode** [comment]
@Formasitchijoh are you an Outreachy (Internship) applicant?

**Comment by Formasitchijoh** [comment]
yes i am @Ifycode

**Comment by Ifycode** [comment]
All right, I will update you tomorrow. Thank you for your patience.

**Comment by Formasitchijoh** [comment]
The pleasure is mine @Ifycode
