### ISSUE TITLE
Update cypress version

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#633]
Update cypress to the latest stable version. 
Ensure tests pass with same consistency and nothing is broken after the update

**Comment by shakirandagire** [comment]
Please assign me to this @AmTryingMyBest

**Comment by theobadha** [comment]
@shakirandagire how's this issue going? Any progress or updates?

**Comment by shakirandagire** [comment]
@AmTryingMyBest I had requested to assign me to this ticket but had not been assigned and I started a new issue that I raised a PR for today. 

Have now started on this one at the moment.
