### ISSUE TITLE
[USH-926] CAM 2023 Mobile menu: Close button and share button color gone, Share button missing

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform-client-mzima#636]
**Describe the bug**
Happens for the web client's Mobile menu:
- Close button color is gone
- Share button has two issues it's hidden and the color is probably gone too

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the map view or any of the 4 views of the web client mzima: https://mzima-release.staging.ush.zone/map
2. Resize the browser to mobile or tablet
3. Click on the hamburger menu to open the mobile menu
4. See that close button no longer has color and share button is missing and no longer at the bottom of the mobile menu.

**Expected look (Screenshot)**
See screenshot for how the close and share button is supposed to look like in the mobile menu

![Image](https://github.com/ushahidi/platform-client-mzima/assets/45185388/87b0554f-2486-4d97-a3eb-61850968fd19)

Note: If you can't see the screenshot added on github, open the issue on linear (request for access to linear through our Gitter community channel or on slack).

**Additional context**
- It's possible that the color of the share button is affected too. Check this out too when you fix.
- Also see comments on this PR to help understand better: https://github.com/ushahidi/platform-client-mzima/pull/382

<sub>[USH-926](https://linear.app/ushahidi/issue/USH-926/cam-2023-mobile-menu-close-button-and-share-button-color-gone-share)</sub>

**Comment by oyenuga17** [comment]
please assign me @Ifycode

**Comment by Ifycode** [comment]
Assigned to you @oyenuga17 
Thank you.
