### ISSUE TITLE
[USH-927] Mobile Client: Back button not working once you try to search for a deployment

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform-client-mzima#637]
**Describe the bug**
Back button not working once you try to search for a deployment

**To Reproduce**
1. Open mzima mobile client in xcode or android studio
2. Go to profile > switch deployment, you will find the deployments screen where there is a search input and list of deployments to choose from
3. Click on the search input to open up search in full screen
4. Click on the back button to try to go back to the deployments screen
5. See that the back button does not work

**Expected behavior**
Back button should take user back to the deployments screen

**Screenshots**

![Image](https://github.com/ushahidi/platform-client-mzima/assets/45185388/50292ef3-4850-4822-895d-f0bf5b7b1109)

If you can't see the screenshot added on github, open the issue on linear (request for access to linear through our Gitter community channel or on slack).

<sub>[USH-927](https://linear.app/ushahidi/issue/USH-927/mobile-client-back-button-not-working-once-you-try-to-search-for-a)</sub>

**Comment by shakirandagire** [comment]
@Ifycode Could you please assign me to this issue?

**Comment by Ifycode** [comment]
Nice and interesting pick. Assigned to you @shakirandagire 👌

**Comment by shakirandagire** [comment]
Thanks @Ifycode. Looking forward to exploring it.

**Comment by shakirandagire** [comment]
@Ifycode I am currently installing Android Studio which is taking quite some time. 
But I will be able to start work after it is done.

**Comment by shakirandagire** [comment]
@Ifycode I have finished to setup the mobile application but when I run the android app using 
`npm run mobile:android`, it stops running like in image below and does not show up in the emulator. 
<img width="1512" alt="Screenshot 2023-10-25 at 16 30 55" src="https://github.com/ushahidi/platform-client-mzima/assets/6957960/2dc91b52-cad9-4e9f-942a-5ae759984c15">

Please note that the `npm run mobile:serve` is working as expected.

**Comment by Ifycode** [comment]
Github sometimes have issues with images these days so I can't see the issue you are showing me in the image. Can we take this to the community channel?
Not the one for Outreachy. Use the community channel for this discussion: https://gitter.im/ushahidi/Community

**Comment by shakirandagire** [comment]
@Ifycode Thanks for the advice,  I have put the question in the community channel

**Comment by Ifycode** [comment]
Hi @shakirandagire how far with this issue ticket?

**Comment by shakirandagire** [comment]
@Ifycode The setup has been so data intensive for the emulators, SDKs and other installations.
 But last night I finished everything though the emulator is not showing the application when i click the play button.

**Comment by shakirandagire** [comment]
@Ifycode Been learning more about Ionic to prepare myself for future tickets on the mobile front.

**Comment by Ifycode** [comment]
Thank you for the feedback @shakirandagire

**Comment by Ifycode** [comment]
Would you like my help at any point with this ticket? @shakirandagire

**Comment by shakirandagire** [comment]
@Ifycode 
You are welcome.
In regards to the ticket, I had been unassigned from it. 
So I had stopped working on it.
But I could resume work on it if possible.

**Comment by Ifycode** [comment]
Oh... Wow... This is not my doing. Sorry about this. We have an integration with linear that probably is doing things on its own. I'm not sure what triggered it to unassign you. I'm also still learning how it works.
@shakirandagire 

I've assigned you again. Please continue working on this issue if you still wish to take it on. If linear misbehaves, please ignore it. I will look into it.

**Comment by shakirandagire** [comment]
@Ifycode An update on the PR.
I have realized the following:
The back button already has the functionality of removing the search results for the deployments.

Implementation of the redirect by giving the button another function has been a bit tricky as in all instances the functionality for hiding search results is completely removed.

The redirect is to a different section of the choose-deployment page and not to another url.

Been trying out some redirection concepts like `router.navigate` and also `routerLink` to the back button but it has not yet worked out for sections.

Do you have any pointers on how to handle this?

**Comment by Ifycode** [comment]
Hmm. Nice one @shakirandagire
I will check and should hear from me between now and Monday.

**Comment by shakirandagire** [comment]
Thanks @Ifycode looking forward to the response 😄

**Comment by Ifycode** [comment]
Referencing the thread on Github: [https://github.com/ushahidi/platform-client-mzima/issues/637#issuecomment-1805685225](https://github.com/ushahidi/platform-client-mzima/issues/637#issuecomment-1805685225)

Not yet. You should get more update before the end of today.

**Comment by shakirandagire** [comment]
@Ifycode Looking forward to the update

**Comment by Ifycode** [comment]
Hello @shakirandagire 
Sorry I was not able to check to completely check this issue out as planned or intended for health reasons.
I no longer oversee this issue. You may have to check with @webong (Wisdom) for this issue from now on @shakirandagire 

> Please note, [the last comment](https://github.com/ushahidi/platform-client-mzima/issues/637#issuecomment-1819228059) was linear not cooperating as expected - that particular response was directed to someone else.

**Comment by shakirandagire** [comment]
Thanks @Ifycode for the response. Sorry about your health. 
Will reach out to @webong for sure

**Comment by Mh-Asmi** [comment]
@wisdom is working on this issue yesterday he reported  he fixed it and he will move it to QA when he create the new instance of mobile app. I hope this will happen later today

**Comment by Mh-Asmi** [comment]
@wisdom can we move it to QA ?

**Comment by Mh-Asmi** [comment]
thank you @maxmwandigha

**Comment by Mh-Asmi** [comment]
@wisdom 
I noticed the PR is approved, can you merge it if it's ready?
