### ISSUE TITLE
Short text field submission fails

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#644]
During the post submission, the short text field is not detected in the CI environment. Figure out why, and a fix for it other than removing or skipping that field.

**Comment by Emuohwo** [comment]
@AmTryingMyBest Please I need more clarification on what's to be done here. I'm sure I will be able to fix it.

**Comment by oyenuga17** [comment]
@AmTryingMyBest took a stab at this and was able to fix it on my local. The issue also affects some other fields like title, decimal field, integer field and date field. Should I go ahead and create a pr for it?
