### ISSUE TITLE
Some elements lack unique selectors that would be used by automation tests. Part 1

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#653]
- [ ] Look through tests 1-4.  (Login, Roles, Users, Surveys)
- [ ] Verify that all elements in the tests are accessed using unique attribute in the format `[data-qa=""]`
- [ ] Where an element is accessed differently, add the unique attributes to the elements, and update the tests to use these attributes.

**Comment by oyenuga17** [comment]
Hi @AmTryingMyBest please I would love to take on this task 😊
