### ISSUE TITLE
Some elements lack unique selectors that would be used by automation tests. Part 2

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#654]
- [ ] Look through tests 1-4.  (Categories, Posts, Collections, EditPosts)
- [ ] Verify that all elements in the tests are accessed using unique attribute in the format `[data-qa=""]`
- [ ] Where an element is accessed differently, add the unique attributes to the elements, and update the tests to use these attributes.

**Comment by shakirandagire** [comment]
@AmTryingMyBest Could you assign me to this issue

**Comment by shakirandagire** [comment]
@AmTryingMyBest Update on the issue.
I have been able to work on some unique selectors but not all of them.
I am currently having issues with some form fields that are shared on different pages.
