### ISSUE TITLE
e2e-add child category

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#664]
Categories have child categories under them. A child category takes on the permissions of the parent category it is created under.
- Navigate to categories page
- Create a category as a parent category
- Who can see the category: 
         - Admin, Translation, Technology
- Create a category as a child category under the parent category (Select Parent Category that was created in earlier step)
- Verify child category created listed under Parent category
- Open child category
- Verify visibility matches parent category

**Comment by oyenuga17** [comment]
@AmTryingMyBest I'd love to give this a try while I wait for the data on the filter related tasks 😊
