### ISSUE TITLE
e2e-verify Share button contents

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#665]
The Share button appears on various pages of the platform. Let's verify the contents of the link to be shared that appears on the modals on the different pages.

- [ ] In Map page, click Share button
- [ ] Verify link in web address contains '..../map'
- [ ] Verify Twitter and Facebook buttons have correct links to twitter and facebook respectively
- [ ] Navigate to Data View
- [ ] Verify link in web address contains '../feed?page=1'

**Comment by shakirandagire** [comment]
@AmTryingMyBest Could you assign me to this issue.
