### ISSUE TITLE
e2e-verify Share button for post

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#666]
- [x] Open a post
- [x] Verify link in web address contains '../feed/102642/view?page=1&mode=POST'

**need to find an ID for specific post

**Comment by shakirandagire** [comment]
@AmTryingMyBest Could you assign me to this.

**Comment by shakirandagire** [comment]
@AmTryingMyBest am still working on the PR for this issue.
We're you able to finish it or it was closed by mistake.
Hadnot yet implemented the specific id in URL part

**Comment by theobadha** [comment]
@shakirandagire revisit this, update and raise a new PR for it.  🙏

**Comment by shakirandagire** [comment]
@AmTryingMyBest On it
