### ISSUE TITLE
e2e-disable user sign up

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#667]
Sign ups can be disabled for deployments. As a result, the Sign Up link is not available

- [ ] Log in as admin
- [ ] Navigate to settings
- [ ] Click on Disable User sign up
- [ ] Save changes
- [ ] Verify the Disable user sign up checkbox stays checked
- [ ] Log out
- [ ] Verify the Sign Up link is unavailable. Log in button should have only Log In fields and no Sign up links

**Comment by oyenuga17** [comment]
@AmTryingMyBest This issue looks interesting, please I would love to try it out. 😊 🙏
