### ISSUE TITLE
e2e-category-creation fails because platform runs in non-english language in the ci

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#689]
In the CI, the platform runs in Arabic! 

As a result, how a particular field is identified by the tests isn't recognized, causing the test to fail

Restructure this test and how this field is identified so that regardless of language the tests run in, they will always pass/fail as expected.
Test => Category creation test
Responsible field => category description field
How field is currently identified => using the field's placeholder text

Suggested fix => add unique attribute to the field, and restructure how the test identifies the field

![Screenshot 2023-11-03 at 17 56 24](https://github.com/ushahidi/platform-client-mzima/assets/38259840/6baa9e1d-f5e5-4a87-b8b0-62ab931967cd)

**Comment by theobadha** [comment]
@oyenuga17 having worked on categories, wanna have a crack at this? :)

**Comment by oyenuga17** [comment]
Yes please, I’d love to try 😇

**Comment by shakirandagire** [comment]
@oyenuga17 @AmTryingMyBest while working on the ticket to add unique selectors I added `[data-qa]="'description'"` instead of using the placeholder, which I used to target the field in the locators and the functions. You can try that out.

**Comment by oyenuga17** [comment]
yeah... I fixed this yesterday already @shakirandagire Thanks.
Github was down so I couldn't push 😆

**Comment by shakirandagire** [comment]
@oyenuga17 Amazing 😄. Glad you were able to fix it.
