### ISSUE TITLE
e2e-verify negative case for login

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#696]
- [x] Attempt login with invalid email format
- [x] Verify user notified of invalid email
- [x] Enter valid email address
- [x] Attempt login with invalid credentials
- [x] Verify login attempt unsuccessful
- [x] Verify user notified of incorrect credentials

**Comment by oyenuga17** [comment]
@AmTryingMyBest can I go ahead with this? 😅
