### ISSUE TITLE
e2e-sign up

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#697]
- [ ] Navigate to Sign Up modal
- [ ] Fill in all required values (including Terms and Conditions checkbox)
- [ ] Verify Sign Up button becomes enabled
- [ ] Empty name field
- [ ] Sign Up button becomes disabled
- [ ] Alter email field contents - enter invalid format email
- [ ] Sign Up button becomes disabled
- [ ] Enter valid format email
- [ ] Sign Up button is enabled
- [ ] Verify Privacy Policy link is "ushahidi.com/privacy-policy"
- [ ] Verify Terms and Conditions link is "ushahidi.com/terms-of-service"
- [ ] Complete sign up
- [ ] Verify user is logged in after Sign Up
- [ ] Verify name matches name provided
- [ ] Verify email matches email provided

**Comment by oyenuga17** [comment]
@AmTryingMyBest I'm done with #696 and I'd love to pick this up next if possible ☺️

**Comment by theobadha** [comment]
@oyenuga17 please rename signup to user-signup. Also, in this list in the task, check against each step covered in the test. :)

**Comment by oyenuga17** [comment]
> @oyenuga17 please rename signup to user-signup. Also, in this list in the task, check against each step covered in the test. :)

Okay, on it 👍
