### ISSUE TITLE
Make deployment private

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#718]
When a deployment is made private, visibility is restricted to only logged in users. Even for public posts.

- [x] Navigate to settings page
- [x] Click on Make this deployment private to checkbox to make public deployment private
- [x] Click Save
- [x] Verify the checkbox remains checked
- [x] Logout
- [x] Verify user is logged out and deployment is private
  - [x] Login modal should pop up, saying Access Denied
  - [x] Path should end with ".../forbidden"
  - [x] Login modal has contact email as seen in Contact section

**Comment by theobadha** [comment]
@shakirandagire remember to mark through checkpoints where available in the issues.

**Comment by shakirandagire** [comment]
@AmTryingMyBest thanks for the reminder. Will endeavour to do that
