### ISSUE TITLE
Change contact email address

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#719]
- [x] Change the deployment email address. (it can be a random but valid email address)
- [x] Save the change
- [x] Verify in the left side detail column that the change is reflected

**Comment by theobadha** [comment]
@shakirandagire you missed the last step in the checkpoints above. The last point should check that the email has changed on the navbar on the left. 
![Screenshot 2024-01-24 at 18 15 48](https://github.com/ushahidi/platform-client-mzima/assets/38259840/6611d820-7093-4688-812e-805f9e124eb1)

**Comment by shakirandagire** [comment]
@AmTryingMyBest , oh completely forgot that

**Comment by theobadha** [comment]
This step may present a bit of trouble though, since the changes may not automatically show on the page. You may need to reload. This is a known issue with the site and there's a ticket in the backlog for it.

**Comment by theobadha** [comment]
Issue for more info: https://linear.app/ushahidi/issue/USH-956/saving-changes-general-settings-doesnt-reflect-on-client-until-refresh

**Comment by shakirandagire** [comment]
I presume I can create a reload in the tests and revert the changes when the ticket is finished.

**Comment by theobadha** [comment]
There's probably no need to revert these changes. They don't affect any other tests and the environment is rebuilt fresh each time so it should be fine.
