### ISSUE TITLE
Survey Configuration - Hide exact Time information

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#725]
Posts sent in have a timestamp of when they were submitted shown on the post. By default the option to hide the exact time information is disabled. In this test, we will enable hiding the exact time information and verify that exact time information is hidden in posts

Test Steps
- [x]  As an admin, while logged in, open a survey in edit mode Settings -> Surveys -> Click on a Survey
- [x]  Click on Configure Tab
- [x]  Hide exact time information is disabled by default
- [x]  Click toggle switch to enable Hide exact time information
- [x]  Save
- [x]  Log out as admin
- [x]  Submit a post to the survey above
- [x]  Verify that time information on the post is an ambiguous time from when the post is submitted

**Comment by ccokeke0023** [comment]
Hey @AmTryingMyBest ,

I would like to  work on this issue.
Could you assign me the ticket so I can take it up?

Thanks
