### ISSUE TITLE
Clean up LoginFunctions and SignUpFunctions of {force: true} 

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#759]
The {force: true} parameter has specific uses, and we really shouldn't use it for each cypress command.
{Force: true} may actually give false positives in some instance so we should be a bit cautious of when and how often we use it.

The task here is to go through the LoginFunctions and SignUpFunctions files and remove the parameter where it's unnecessary.

**Comment by shakirandagire** [comment]
@AmTryingMyBest I added the {force: true} because the parent element has CSS that is hidden so the suggested solution was using the {force: true}. I am going to look into an alternative solutions for this
