### ISSUE TITLE
Users - Verify list of users is visible on visiting users page

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#774]
We have tests that adds a User. This is an additional check.
In the users page:
- [x] Verify the list of users is visible. 
![Screenshot 2024-02-13 at 14 37 10](https://github.com/ushahidi/platform-client-mzima/assets/38259840/a458bc1d-ca33-436a-8f4c-d6ffd60789b5)
This screenshot is the current list of users. The best way may be to use email to verify the list, since that's the unique field while names are duplicated. Though we could still use name for accurate results. Food for thought.

**Comment by ccokeke0023** [comment]
Hi @AmTryingMyBest ,
I am an outreachy applicant for the current cohort. I would like to work on this task if it is still available.
Could you confirm so I can take it up.
Thanks

**Comment by sidrakhandev** [comment]
@ccokeke0023 can you guide me how to access the test environment.
