### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Formasitchijoh** [ushahidi/platform-client-mzima#789]
### Subject:
Issue with setting up Platform-client-mzima mobile app on Android Studio

Hello @tuxpiper, @AmTryingMyBest,  @Ifycode 

I hope you're doing well. I'm currently working on setting up the Platform-client-mzima project and have encountered an error while trying to run the mobile app on a simulator in Android Studio. I would appreciate your assistance in resolving this issue.
Here are the details:

### Steps taken:

- [x] Successfully set up the Platform-client-mzima project for the web.
- [x] Set up the mobile application on the web, following the provided setup guide.
- [x] Attempted to run the mobile app on a simulator in Android Studio.
### Error encountered:
I received the following error message:

![failed](https://github.com/ushahidi/platform-client-mzima/assets/76694292/3beca83d-7370-407a-923a-e20737cd70d5)

 ### Expected behavior: 
 I expected the mobile app to run on the simulator without any errors, similar to the successful setup of the web version.I have already followed the setup guide and reviewed some of the mobile scripts, which appear to be working perfectly. However, I'm unsure about the cause of this specific error.Could you please review my steps and let me know if there's anything I might have missed or any additional configurations required to resolve this issue? Your guidance and assistance would be greatly appreciated

**Comment by Ifycode** [comment]
Hello @Formasitchijoh Nice work with setting up so far. Sorry just found this.
Please use our discord channel so that we can discuss this further there. Here's the invite link (Link expires in 7 days): https://discord.com/invite/Dkv6Mcps

**Comment by Formasitchijoh** [comment]
Thank you @Ifycode , i'll do that

**Comment by tuxpiper** [comment]
re: `NODE_ENV is not recognized as an internal or external command`

Seems that Windows is choking up on the UNIX way of setting environment variables.

Maybe cross-env or something similar can help with that: https://www.npmjs.com/package/cross-env

**Comment by Formasitchijoh** [comment]
Hello @tuxpiper, @Ifycode,

I appreciate your assistance, and I wanted to share the steps I took to successfully resolve the issues with running the project. This might be helpful for others encountering similar challenges.

 + Installed Nx build tool globally:
npm install -g nx
This step was necessary to utilize the Nx build tool, which leverages project configurations.

+ Modified the project.json file for the Android platform:
I removed the explicit setting of NODE_ENV in Android build scripts. This change allows the build system to automatically determine the environment based on the project's build configuration.

+ Resolved Android Gradle plugin version compatibility:
Encountered an error about incompatible AGP versions (8.2.0 vs. 8.1.0). I addressed this by setting the AGP version to 8.1.0 to ensure compatibility.

![solved](https://github.com/ushahidi/platform-client-mzima/assets/76694292/0dc8ce10-1e4b-4d68-ab40-6ffb8988683f)

I hope these steps are helpful, and I would like to confirm if this approach, especially the modification in the project.json file, aligns with best practices. If you have any suggestions or corrections, please feel free to let me know.

Thank you again for your support!

**Comment by tuxpiper** [comment]
>     Installed Nx build tool globally:
>     npm install -g nx
>     This step was necessary to utilize the Nx build tool, which leverages project configurations.
> 
>     Modified the project.json file for the Android platform:
>     I removed the explicit setting of NODE_ENV in Android build scripts. This change allows the build system to automatically determine the environment based on the project's build configuration.
> 
>     Resolved Android Gradle plugin version compatibility:
>     Encountered an error about incompatible AGP versions (8.2.0 vs. 8.1.0). I addressed this by setting the AGP version to 8.1.0 to ensure compatibility.


This sounds quite reasonable to me. Thank you @Formasitchijoh  ! Would you be up to put this changes in a pull request?

@webong @ushahidlee I'd ask you to review

**Comment by Formasitchijoh** [comment]
Hello @tuxpiper , i'll be glad to do that, thank you

**Comment by Chiemezuo** [comment]
I just made a fix for this using the `cross-env` library @tuxpiper 
I installed the package and updated the `project.json` file in the `app/mobile-mzima-client` directory. I'll link the PR shortly.

**Comment by tuxpiper** [comment]
Approved 👍
