### ISSUE TITLE
Incorrect dependency version specified for @capacitor/app in package.json

### ISSUE THREAD

**Issue by RWUBAKWANAYO** [ushahidi/platform-client-mzima#843]
## Describe the bug:

When running `npm install` in the `mobile-mzima-client` directory of the `ushahidi/platform-client-mzima` repository, an error occurs due to an incorrect dependency version specified for `@capacitor/app` in the `package.json` file.

## To Reproduce:
1. Clone the ushahidi client platform: `git clone git@github.com:ushahidi/platform-client-mzima.git`
2. Navigate to the `mobile-mzima-client` directory: `cd apps/mobile-mzima-client`
3. Run `npm install`

## Expected behavior:
The `npm install` command should successfully install all dependencies without errors.

## Screenshots:

<img width="957" alt="Screen Shot 2024-03-08 at 20 38 21" src="https://github.com/ushahidi/platform-client-mzima/assets/68381641/cd50ee55-1406-47e6-ad64-a0563dfe4431">

## Desktop:
 - OS:  iOS
 - Browser: Chrome
 - Version: 122

## Additional Context:
- The `package.json` file specifies a minimum version of `^5.6.0` for the `@capacitor/app` dependency.
- The latest available version of `@capacitor/app` on npm is [`5.0.7`](https://www.npmjs.com/package/@capacitor/app), which is less than the specified version in the `package.json` file.
- This discrepancy results in `npm install` failing to resolve the dependency, causing the installation process to fail.

**Comment by Chiemezuo** [comment]
I've made a fix for this.
I'll be linking a PR to it shortly.
