### ISSUE TITLE
Update General Settings tests

### ISSUE THREAD

**Issue by theobadha** [ushahidi/platform-client-mzima#963]
In the general settings test steps, we made changes to the general settings. Then to verify these settings took effect, we may have had to reload the page. 
The platform has since been updated, and the page doesn't have to be reloaded for changes to come into effect.
Therefore, let's update the tests to match this new flow. 

- [x] After making changes, verify changes come into effect immediately (remove any reloads)

**Comment by Chiemezuo** [comment]
Hi!
Do pardon me if I'm wrong, but does this translate to removing the instances of `cy.reload();` in the `GeneralSettingsFunctions` file, and testing?
